"""Inject generated tables between AUTOGEN markers in the READMEs (idempotent)."""

from __future__ import annotations

import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

SECTIONS = ("METRICS", "CALIBRATION", "XAI", "GROUPS")


class RenderError(RuntimeError):
    pass


def _marker_pattern(section: str) -> re.Pattern[str]:
    return re.compile(
        rf"(<!-- AUTOGEN:{section}:START -->)(.*?)(<!-- AUTOGEN:{section}:END -->)",
        re.DOTALL,
    )


def render_block(section: str, content: str, run_label: str) -> str:
    return (
        f"<!-- AUTOGEN:{section}:START -->\n"
        f"<!-- generated by `credit-xai report` from results/derived/summary.json "
        f"(run: {run_label}); do not edit by hand -->\n"
        f"{content}\n"
        f"<!-- AUTOGEN:{section}:END -->"
    )


def inject(readme_path: str | Path, tables: dict[str, str], run_label: str) -> None:
    path = Path(readme_path)
    if not path.exists():
        raise RenderError(f"README not found: {path}")
    text = path.read_text(encoding="utf-8")
    for section in SECTIONS:
        block = tables[section.lower()]
        replacement = render_block(section, block, run_label)
        pattern = _marker_pattern(section)
        if not pattern.search(text):
            raise RenderError(f"{path}: missing AUTOGEN markers for section {section}")

        def replace_marker(_match: re.Match[str], replacement_value: str = replacement) -> str:
            return replacement_value

        text = pattern.sub(replace_marker, text, count=1)
    path.write_text(text, encoding="utf-8", newline="\n")
    logger.info("injected %d sections into %s", len(SECTIONS), path)
